version: 2
updates:
  - package-ecosystem: "npm"     # 适用于 pnpm 也 OK
    directory: "/"               # 根目录下的 package.json
    schedule:
      interval: "daily"          # 每天检查一次
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 0  # 禁掉普通版本更新，只保留安全更新 PR
