import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/pages/": [
    {
      text: "前端",
      icon: "web",
      prefix: "01.前端/",
      collapsible: true,
      children: [
        {
          text: "CSS",
          icon: "css",
          prefix: "10.CSS/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "JavaScript",
          icon: "javascript",
          prefix: "20.JavaScript/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "Vue",
          icon: "vue",
          prefix: "50.Vue/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "树莓派",
      icon: "raspberrypi",
      prefix: "02.树莓派/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "All In One",
      icon: "all-in-one",
      prefix: "03.All In One/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "技术",
      icon: "code",
      prefix: "05.技术/",
      collapsible: true,
      children: [
        {
          text: "技术文档",
          icon: "code-doc",
          prefix: "05.技术文档/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "技术教程",
          icon: "code-tutorial",
          prefix: "10.技术教程/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "Git工具",
          icon: "git",
          prefix: "15.Git工具/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "Nodejs",
          icon: "nodejs",
          prefix: "20.Nodejs/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "Linux安全",
          icon: "linux-security",
          prefix: "25.Linux安全/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "博客建设",
      icon: "blog-build",
      prefix: "20.博客建设/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "实用技巧",
      icon: "practical-skills",
      prefix: "50.实用技巧/",
      collapsible: true,
      children: [
        {
          text: "VSCode",
          icon: "vscode",
          prefix: "02.VSCode/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "Windows修改",
          icon: "windows-modify",
          prefix: "05.Windows修改/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "随笔",
      icon: "essay",
      prefix: "90.随笔/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "收藏夹",
      icon: "collection",
      prefix: "95.收藏夹/",
      collapsible: true,
      children: "structure",
    },
  ],
});
